<?php
register_post_type('comparison', array(
	'label' => 'Vergleiche',
	'description' => '',
	'hierarchical' => false,
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
	),
	'public' => true,
	'exclude_from_search' => false,
	'publicly_queryable' => true,
	'can_export' => true,
	'delete_with_user' => 'null',
	'labels' => array(
	),
	'menu_position' => 20,
	'menu_icon' => 'dashicons-admin-post',
	'show_ui' => true,
	'show_in_menu' => true,
	'show_in_nav_menus' => true,
	'show_in_admin_bar' => true,
	'rewrite' => array(
		'slug' => 'vergleich',
		'with_front' => true,
		'feeds' => true,
		'pages' => true,
	),
	'has_archive' => 'vergleiche',
	'show_in_rest' => true,
	'rest_base' => '',
	'rest_controller_class' => 'WP_REST_Posts_Controller',
	'acfe_archive_template' => '',
	'acfe_archive_ppp' => 10,
	'acfe_archive_orderby' => 'date',
	'acfe_archive_order' => 'DESC',
	'acfe_single_template' => '',
	'acfe_admin_archive' => false,
	'acfe_admin_ppp' => 10,
	'acfe_admin_orderby' => 'date',
	'acfe_admin_order' => 'DESC',
	'capability_type' => 'post',
	'capabilities' => array(
	),
	'map_meta_cap' => NULL,
));

register_post_type('products', array(
	'label' => 'Produkte',
	'description' => '',
	'hierarchical' => false,
	'supports' => array(
	),
	'taxonomies' => array(
	),
	'public' => true,
	'exclude_from_search' => false,
	'publicly_queryable' => true,
	'can_export' => true,
	'delete_with_user' => 'null',
	'labels' => array(
	),
	'menu_position' => 20,
	'menu_icon' => 'dashicons-admin-post',
	'show_ui' => true,
	'show_in_menu' => true,
	'show_in_nav_menus' => true,
	'show_in_admin_bar' => true,
	'rewrite' => true,
	'has_archive' => 'produkte',
	'show_in_rest' => false,
	'rest_base' => '',
	'rest_controller_class' => 'WP_REST_Posts_Controller',
	'acfe_archive_template' => '',
	'acfe_archive_ppp' => 10,
	'acfe_archive_orderby' => 'date',
	'acfe_archive_order' => 'DESC',
	'acfe_single_template' => '',
	'acfe_admin_archive' => false,
	'acfe_admin_ppp' => 10,
	'acfe_admin_orderby' => 'date',
	'acfe_admin_order' => 'DESC',
	'capability_type' => 'post',
	'capabilities' => array(
	),
	'map_meta_cap' => NULL,
));

register_post_type('index', array(
	'label' => 'Index',
	'description' => '',
	'hierarchical' => false,
	'supports' => array(
		0 => 'title',
	),
	'taxonomies' => array(
	),
	'public' => true,
	'exclude_from_search' => false,
	'publicly_queryable' => true,
	'can_export' => true,
	'delete_with_user' => 'null',
	'labels' => array(
	),
	'menu_icon' => 'dashicons-admin-post',
	'show_ui' => true,
	'show_in_menu' => true,
	'show_in_nav_menus' => true,
	'show_in_admin_bar' => true,
	'rewrite' => true,
	'has_archive' => true,
	'show_in_rest' => false,
	'rest_base' => '',
	'rest_controller_class' => 'WP_REST_Posts_Controller',
	'acfe_archive_template' => '',
	'acfe_archive_ppp' => 10,
	'acfe_archive_orderby' => 'date',
	'acfe_archive_order' => 'DESC',
	'acfe_single_template' => '',
	'acfe_admin_archive' => false,
	'acfe_admin_ppp' => 10,
	'acfe_admin_orderby' => 'date',
	'acfe_admin_order' => 'DESC',
	'capability_type' => 'post',
	'capabilities' => array(
	),
	'map_meta_cap' => NULL,
));
